import type { UiAzit, UiAzitMember, UiAzitTopic, UiChatMessage } from "@/types/azit/ui";

export const AZIT_LIST: UiAzit[] = [
  {
    id: "azit-run",
    name: "러닝 메이트의 30일",
    memberCount: 4,
    maxMembers: 5,
    description: "매일의 러닝과 작은 성취를 영상으로 나누는 방이에요.",
    coverGradient: "linear-gradient(104deg, #2e1f52 0%, #7a5cfa 100%)",
    topicCount: 3,
    visibility: "public",
    category: "운동",
    ownerName: "안유진",
    todayVideoCount: 4,
    videoCount: 23,
    topicSummary: "아침 러닝 · 식단",
    thumbnailSrc: "/plip/daily-loop/room-thumbnail.png",
    joined: false,
  },
  {
    id: "azit-diet",
    name: "식단 기록방",
    memberCount: 6,
    maxMembers: 10,
    description: "하루 한 끼를 영상으로 남겨요.",
    coverGradient: "linear-gradient(135deg, #3a1f5c, #1e228a)",
    topicCount: 1,
    visibility: "public",
    category: "성장",
    ownerName: "건강한한끼",
    joined: false,
  },
  {
    id: "azit-hangang",
    name: "주말 한강 산책 모임",
    memberCount: 3,
    maxMembers: 5,
    description: "가볍게 걷고 그날의 풍경을 한 편씩 남겨요.",
    coverGradient: "linear-gradient(135deg, #3a1f5c, #1e228a)",
    topicCount: 2,
    visibility: "private",
    category: "일상",
    ownerName: "박서준",
    todayVideoCount: 0,
    topicSummary: "주말 산책 · 오늘의 풍경",
    joined: false,
  },
  {
    id: "azit-walk",
    name: "새벽 러너스",
    memberCount: 4,
    maxMembers: 5,
    description: "매일 아침 러닝을 영상으로 나눠요.",
    coverGradient: "linear-gradient(135deg, #1a4d6e, #0b1753)",
    topicCount: 6,
    visibility: "private",
    ownerName: "안지민",
    todayVideoCount: 4,
    thumbnailSrc: "/plip/v13/azit-avatar.svg",
    joined: true,
  },
  {
    id: "azit-gym",
    name: "영어 1분",
    memberCount: 5,
    maxMembers: 8,
    description: "하루 1분 영어 말하기.",
    coverGradient: "linear-gradient(135deg, #0f3d3a, #032426)",
    topicCount: 4,
    visibility: "public",
    ownerName: "하린",
    todayVideoCount: 3,
    thumbnailSrc: "/plip/v13/azit-avatar.svg",
    joined: true,
  },
  {
    id: "azit-cook",
    name: "주말 드로잉",
    memberCount: 3,
    maxMembers: 5,
    description: "주말마다 한 장의 그림을 남겨요.",
    coverGradient: "linear-gradient(135deg, #3a1f5c, #1e228a)",
    topicCount: 5,
    visibility: "public",
    ownerName: "유나",
    todayVideoCount: 2,
    thumbnailSrc: "/plip/v13/azit-avatar.svg",
    joined: true,
  },
  {
    id: "azit-study",
    name: "퇴근 후 1시간 공부",
    memberCount: 3,
    maxMembers: 5,
    description: "퇴근 후 한 시간만 집중해서 공부해요.",
    coverGradient: "linear-gradient(135deg, #2e1f52, #7a5cfa)",
    topicCount: 2,
    visibility: "public",
    category: "공부",
    thumbnailSrc: "/plip/daily-loop/explore-thumb-1.png",
    joined: false,
  },
  {
    id: "azit-dish",
    name: "하루 한 접시",
    memberCount: 5,
    maxMembers: 8,
    description: "오늘 한 끼를 접시 위로 남겨요.",
    coverGradient: "linear-gradient(135deg, #3a1f5c, #1e228a)",
    topicCount: 1,
    visibility: "public",
    category: "일상",
    thumbnailSrc: "/plip/daily-loop/explore-thumb-2.png",
    joined: false,
  },
];

export const AZIT_MEMBERS: UiAzitMember[] = [
  { id: "m1", name: "플립이", role: "owner" },
  { id: "m2", name: "클립러", role: "member" },
  { id: "m3", name: "요리왕", role: "member" },
  { id: "m4", name: "산책러", role: "member" },
];

export const AZIT_TOPICS: UiAzitTopic[] = [
  { id: "t1", title: "이번 주 하이라이트", clipCount: 12 },
  { id: "t2", title: "인증 챌린지", clipCount: 8 },
  { id: "t3", title: "자유 토픽", clipCount: 21 },
];

export const AZIT_CHAT: UiChatMessage[] = [
  {
    id: "c1",
    senderName: "민지",
    body: "오늘 영상 올리기 전에 태그를 먼저 정할까요?",
    isMine: false,
    time: "오후 8:40",
  },
  {
    id: "c2",
    senderName: "나",
    body: "좋아요. 후보를 세 개로 만들어봤어요!",
    isMine: true,
    time: "오후 8:42",
    replyTo: { name: "민지", excerpt: "태그를 먼저 정할까요?" },
  },
];

export function getAzitById(azitId: string): UiAzit | undefined {
  return AZIT_LIST.find((azit) => azit.id === azitId);
}
