export const ROUTES = {
  home: "/home",
  intro: "/",
  login: "/login",
  signup: "/signup",
  signupProfile: "/signup/profile",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  create: "/create",
  diary: {
    root: "/diary",
    date: (date: string) => `/diary/${date}` as const,
    themes: {
      root: "/diary/themes",
      detail: (themeId: string) => `/diary/themes/${themeId}` as const,
    },
  },
  azit: {
    root: "/azit",
    create: "/azit/create",
    createSettings: "/azit/create/settings",
    detail: (azitId: string) => `/azit/${azitId}` as const,
    enter: (azitId: string) => `/azit/${azitId}/enter` as const,
    invite: (azitId: string) => `/azit/${azitId}/invite` as const,
    profile: (azitId: string) => `/azit/${azitId}/profile` as const,
    joined: (azitId: string) => `/azit/${azitId}/joined` as const,
    members: (azitId: string) => `/azit/${azitId}/members` as const,
    topics: (azitId: string) => `/azit/${azitId}/topics` as const,
    manage: (azitId: string) => `/azit/${azitId}/manage` as const,
    calendar: (azitId: string) => `/azit/${azitId}/calendar` as const,
    upload: (azitId: string) => `/azit/${azitId}/upload` as const,
    safety: (azitId: string) => `/azit/${azitId}/safety` as const,
    chat: (azitId: string) => `/azit/${azitId}/chat` as const,
    poll: (azitId: string) => `/azit/${azitId}/chat/poll` as const,
    pollEdit: (azitId: string) => `/azit/${azitId}/chat/poll/edit` as const,
    search: "/azit/search",
  },
  agit: {
    root: "/agit",
  },
  viewer: {
    clip: (clipId: string) => `/viewer/${clipId}` as const,
    edit: (clipId: string) => `/viewer/${clipId}/edit` as const,
  },
  shop: {
    root: "/shop",
    item: (itemId: string) => `/shop/items/${itemId}` as const,
    purchase: (itemId: string) => `/shop/items/${itemId}/purchase` as const,
    charge: "/shop/charge",
    wishlist: "/shop/wishlist",
    myItems: "/shop/my-items",
    points: "/shop/points",
    refund: "/shop/refund",
    refundHistory: "/shop/refund/history",
  },
  mypage: {
    root: "/mypage",
    profile: "/mypage/profile",
    password: "/mypage/profile/password",
    notifications: "/mypage/notifications",
    settings: "/mypage/settings",
  },
  /** plip-video Phase 0-F — user-app 본 UI와 분리 (route group `(capture)`) */
  capture: {
    video: "/video",
    videoApi: "/video-api",
  },
} as const;
