name: Sync to Personal Repo

on:
  push:
    branches:
      - develop # 기본 브랜치가 main이라면 main으로 변경
  workflow_dispatch:

jobs:
  sync:
    if: github.repository == 'team-yes-bang/plip-user-app'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repoA
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Force Push to repoB
        env:
          TOKEN: ${{ secrets.PERSONALACCESSTOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git remote add target https://x-access-token:${TOKEN}@github.com/sjl0430/plip-user-app.git
          git push target develop:develop --force
